### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef


### login
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "123"
}

###
@token = {{login.response.body.data.token}}

### logout user
POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}


### get users
GET  {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### get user by id
GET  {{host}}/api/users/1
Accept: application/json
Authorization: Bearer {{token}}

### post user
POST {{host}}/api/users 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name":  "Vásárló2",
    "email": "vasarlo2@example.com",
    "password": "123"
}

### patch user
PATCH {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "No Boss"
}

### delete user
DELETE {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### User csak önmagát törölheti
DELETE {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### A bejelentkezett user a jelszavát módosítja
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "vasarlo2",
    "email": "vasarlo2@example.com"
}

### A bejelentkezett user egy adatát módosítja. A role tiltott
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
     "name": "admin1"
}

### A bejelnkezett felhasználó jelszó cseréje
PATCH {{host}}/api/usersmeupdatepassword
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "oldpassword": "ronaldo",
    "newpassword": "123",
    "newpassword_confirmation": "123"
}

### A bejelentkezett user önmagát lekérheti
GET  {{host}}/api/usersme
Accept: application/json
Authorization: Bearer {{token}}

//----------------------------------------------------

### teszt
get {{host}}/api/x

### --- roles ---------------------------------------

### get roles
get {{host}}/api/roles
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### get role by id
get {{host}}/api/roles/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post role
POST  {{host}}/api/roles
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "role":"naplopó"
}

### delete role by id
delete {{host}}/api/roles/6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### update role
PATCH {{host}}/api/roles/7
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "role":"hering"
}


### --- tasks ---------------------------------------------

### get tasks
get {{host}}/api/tasks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### get task by id
get {{host}}/api/tasks/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post task
POST  {{host}}/api/tasks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "roleid":1,
    "personid":416,
    "movieid":77
}

### delete tasks by id
delete {{host}}/api/tasks/10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### update task
PATCH {{host}}/api/tasks/7
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "roleid":1,
    "personid":46,
    "movieid":10
}



